# Generated by Django 4.2.6 on 2023-10-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_blog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='user',
            field=models.EmailField(max_length=254),
        ),
    ]
